
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import {
  PenLine,
  Upload,
  Sparkles,
  Image,
  Wand2,
  FileCode,
  ArrowRight
} from "lucide-react";
import MainLayout from "@/layouts/MainLayout";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";

const Index = () => {
  return (
    <MainLayout>
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-blue-50 py-20">
        <div className="container relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-6">
              <h1 className="text-4xl sm:text-5xl font-bold leading-tight">
                Transform Your <span className="text-blue-600">Handwriting</span> Into Digital Magic
              </h1>
              <p className="text-xl text-gray-600">
                Upload your handwriting samples and our AI will learn to write exactly like you.
                Generate personalized handwritten text for notes, letters, and more.
              </p>
              <div className="flex flex-wrap gap-4">
                <Button size="lg" asChild>
                  <Link to="/upload">
                    Get Started
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
                <Button size="lg" variant="outline" asChild>
                  <Link to="/guide">
                    Learn How It Works
                  </Link>
                </Button>
              </div>
            </div>
            <div className="relative">
              <div className="paper-texture p-8 rounded-lg shadow-lg rotate-2">
                <p className="handwriting ink-blue text-2xl animate-writing">
                  Hello! This is my personal handwriting generated by AI.
                </p>
              </div>
              <div className="absolute -bottom-4 -left-4 paper-texture p-6 rounded-lg shadow-lg -rotate-3">
                <p className="handwriting ink-blue text-xl">
                  Looks just like mine!
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="absolute top-0 right-0 -mt-16 -mr-16 h-64 w-64 rounded-full bg-blue-100/80 blur-3xl"></div>
        <div className="absolute bottom-0 left-0 -mb-16 -ml-16 h-64 w-64 rounded-full bg-blue-200/50 blur-3xl"></div>
      </section>

      {/* How It Works Section */}
      <section className="py-20">
        <div className="container">
          <div className="text-center mb-12 space-y-2">
            <h2 className="text-3xl font-bold">How It Works</h2>
            <p className="text-gray-500 max-w-2xl mx-auto">
              Our AI-powered platform makes it easy to digitize your handwriting in just a few steps.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <Card>
              <CardHeader className="space-y-1">
                <div className="bg-blue-50 w-12 h-12 rounded-full flex items-center justify-center mb-2">
                  <Upload className="h-6 w-6 text-blue-600" />
                </div>
                <CardTitle>Upload</CardTitle>
                <CardDescription>Upload images of your handwriting samples</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-gray-500">
                  Provide at least 20 images of your handwriting. More samples lead to better results.
                </p>
              </CardContent>
              <CardFooter>
                <Button variant="ghost" asChild className="w-full">
                  <Link to="/upload">
                    Upload Samples
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              </CardFooter>
            </Card>

            <Card>
              <CardHeader className="space-y-1">
                <div className="bg-blue-50 w-12 h-12 rounded-full flex items-center justify-center mb-2">
                  <FileCode className="h-6 w-6 text-blue-600" />
                </div>
                <CardTitle>Train</CardTitle>
                <CardDescription>Train the AI model with Google Colab</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-gray-500">
                  Our pre-configured Colab notebook makes training simple with step-by-step instructions.
                </p>
              </CardContent>
              <CardFooter>
                <Button variant="ghost" asChild className="w-full">
                  <Link to="/colab">
                    Training Guide
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              </CardFooter>
            </Card>

            <Card>
              <CardHeader className="space-y-1">
                <div className="bg-blue-50 w-12 h-12 rounded-full flex items-center justify-center mb-2">
                  <Wand2 className="h-6 w-6 text-blue-600" />
                </div>
                <CardTitle>Generate</CardTitle>
                <CardDescription>Generate handwritten text in your style</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-gray-500">
                  Enter any text and watch as the AI generates it in your own handwriting style instantly.
                </p>
              </CardContent>
              <CardFooter>
                <Button variant="ghost" asChild className="w-full">
                  <Link to="/generate">
                    Generate Text
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              </CardFooter>
            </Card>

            <Card>
              <CardHeader className="space-y-1">
                <div className="bg-blue-50 w-12 h-12 rounded-full flex items-center justify-center mb-2">
                  <Image className="h-6 w-6 text-blue-600" />
                </div>
                <CardTitle>Save & Share</CardTitle>
                <CardDescription>Save, download and share your creations</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-gray-500">
                  Download your handwritten text as images, save them to your gallery, or share them directly.
                </p>
              </CardContent>
              <CardFooter>
                <Button variant="ghost" asChild className="w-full">
                  <Link to="/gallery">
                    View Gallery
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-50">
        <div className="container">
          <div className="text-center mb-12 space-y-2">
            <h2 className="text-3xl font-bold">Features</h2>
            <p className="text-gray-500 max-w-2xl mx-auto">
              Our platform offers several powerful features to create authentic handwriting.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white p-6 rounded-lg shadow-sm border">
              <div className="bg-blue-50 w-12 h-12 rounded-full flex items-center justify-center mb-4">
                <PenLine className="h-6 w-6 text-blue-600" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Personal Style Preservation</h3>
              <p className="text-gray-500">
                Our AI captures the unique characteristics of your handwriting, including pressure, slant, and spacing.
              </p>
            </div>

            <div className="bg-white p-6 rounded-lg shadow-sm border">
              <div className="bg-blue-50 w-12 h-12 rounded-full flex items-center justify-center mb-4">
                <Sparkles className="h-6 w-6 text-blue-600" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Authentic Variations</h3>
              <p className="text-gray-500">
                The AI introduces natural variations in your handwriting, just like when you write by hand.
              </p>
            </div>

            <div className="bg-white p-6 rounded-lg shadow-sm border">
              <div className="bg-blue-50 w-12 h-12 rounded-full flex items-center justify-center mb-4">
                <Image className="h-6 w-6 text-blue-600" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Multiple Export Options</h3>
              <p className="text-gray-500">
                Download your generated handwriting as high-quality images in various formats.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-blue-600 text-white">
        <div className="container">
          <div className="max-w-3xl mx-auto text-center space-y-6">
            <h2 className="text-3xl font-bold">Ready to Digitize Your Handwriting?</h2>
            <p className="text-xl text-blue-100">
              Start transforming your handwriting into digital text today.
            </p>
            <Button size="lg" variant="secondary" asChild>
              <Link to="/upload">Get Started Now</Link>
            </Button>
          </div>
        </div>
      </section>
    </MainLayout>
  );
};

export default Index;
